blog/urls.py
from django.conf.urls import url
from .views import *

app_name = 'blog'

urlpatterns = [
    # /blog/
    url(r'^$', PostLV.as_view(), name='index'),
    # /blog/post/ (same as /blog/)
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    # /blog/post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    # /blog/archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    # /blog/2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    # /blog/2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # /blog/2012/nov/18
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # /blog/today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # /blog/tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    # /blog/tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    # /blog/search/
    url(r'^search/$', SearchFormView.as_view(), name='search'),

    # /blog/add/
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    # /blog/change
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    # /blog/pk/update
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name='update'),
    # /blog/pk/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name='delete'),



]

bookmark/urls.py
from django.conf.urls import url
from .views import *


app_name = 'bookmark'

urlpatterns =[
    # /bookmark/
    url(r'^$', BookmarkLV.as_view(), name='index'),
    # /bookmark/숫자/
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

    # /bookmark/add/
    url(r'^add/$', BookmarkCreateView.as_view(), name='add'),
    # /bookmark/change
    url(r'^change/$', BookmarkChangeLV.as_view(), name='change'),
    # /bookmark/pk/update
    url(r'^(?P<pk>[0-9]+)/update/$', BookmarkUpdateView.as_view(), name='update'),
    # /bookmark/pk/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', BookmarkDeleteView.as_view(), name='delete'),
]

bookmark/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from django.contrib.auth.models import User
# Create your models here.

@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    description = models.CharField('DESCRIPTION', max_length=50, blank=True, help_text='simple description text')

    def __str__(self):
        return self.title

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Bookmark
from django.urls import reverse_lazy
from config.views import LoginRequiredMixin

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user) #사용자가 owner로 등록되어있는 bookmark로 필터링

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')



# Create your views here.

bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}

{% block title %}bookmark_change_list.html{% endblock %}

{% load staticfiles %}
{% block content %}

<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/about-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Bookmark</h1>
                        <span class="subheading">Fill in new bookmarks</span>
                    </div>
                </div>
            </div>
        </div>
  </header>

<div id="content">
    <div class="row">
        <div class="col-md-10 col-lg-auto mx-auto">
            <h1>Bookmark List Change</h1>
        </div>
    </div>
    <div class="row"></div>
    <div class="col-md-10 col-lg-auto mx-auto">
        <table class="table table-hover">
            <tr>
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td><a href="{{ item.url }}">{{ item.url }}</a></td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
                <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
            </tr>
        {% endfor %}
        </table>
    </div>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/about-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Bookmark</h1>
                        <span class="subheading">Fill in new bookmarks</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    <h1>Bookmark Delete</h1>

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}Django Bookmark Detail{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/about-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Bookmark</h1>
                        <span class="subheading">Fill in new bookmarks</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div class="container" id="title">
    <div class="row">
        <div class="col-lg-auto col-md-10 mx-auto">
            <h1>{{ object.title }}</h1>
        </div>
        <br/>
        <div class="col-lg-10 col-md-10 mx-auto">
            <ul>
                <li>Editor : {{ object.owner }}</li>
                <li>URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
                <li>Description : {{ object.description }}</li>
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">window.location.hash = '#title';</script>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}

{% block title %}bookmark_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/about-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Bookmark</h1>
                        <span class="subheading">Fill in new bookmarks</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    <form action="." method="post">
        {% csrf_token %}

        {% if form.errors %}
        <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <h4>This is a creation or update form for your bookmark.</h4>

        <fieldset class="aligned">

            <div class="form-row">
                {{ form.title.label_tag }} {{ form.title }}
            </div>

            <div class="form-row">
                {{ form.url.label_tag }} {{ form.url }}
            </div>
        </fieldset>


            <button type="submit" class="btn btn-primary" style="float: right;">Submit</button>



    </form>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}Django Bookmark List{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/about-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Bookmark</h1>
                        <span class="subheading">Fill in new bookmarks</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div class="container" id="title">
    <div class="row">
        <div class="col-lg-auto col-md-10 mx-auto">
            <h1>Bookmark List</h1>
        </div>
    </div>
</div>

<div class="col-lg-8 col-md-10 mx-auto">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">URL Name</th>
            <th scope="col">Owner</th>
        </tr>
        </thead>
        <tbody>
        {% for bookmark in object_list %}
            <tr>
                <th scope="row"><li></li></th>
                <td><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></td>
                <td>{{ bookmark.owner }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
    <script type="text/javascript">window.location.hash = '#title';</script>
{% endblock %}