blog/urls.py
from django.conf.urls import url
from .views import *

app_name = 'blog'

urlpatterns = [
    # /blog/
    url(r'^$', PostLV.as_view(), name='index'),
    # /blog/post/ (same as /blog/)
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    # /blog/post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    # /blog/archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    # /blog/2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    # /blog/2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # /blog/2012/nov/18
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # /blog/today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # /blog/tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    # /blog/tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    # /blog/search/
    url(r'^search/$', SearchFormView.as_view(), name='search'),

    # /blog/add/
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    # /blog/change
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    # /blog/pk/update
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name='update'),
    # /blog/pk/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name='delete'),



]

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse
from tagging.fields import TagField

from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=50, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    tag = TagField()
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)



    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    # save 메소드 재정의.
    def save(self, *args, **kwargs):
        if not self.id: # self.id가 False인 경우, 즉 처음 하는 경우에
            self.slug = slugify(self.title, allow_unicode=True) # slug필드를 title로 저장
        super(Post, self).save(*args, **kwargs) # 기존의 save() 메소드 호출하여 저장.

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from .models import *

from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from django.views.generic.edit import FormView
from .forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from config.views import LoginRequiredMixin

# Create your views here.

class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'


class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        schWord = '%s' % self.request.POST['search_word']
        # 검색하기 위한 ORM, Q를 사용해야한다고한다.
        post_list = Post.objects.filter(Q(title__icontains=schWord) | Q(description__icontains=schWord) |
                                        Q(content__icontains=schWord)).distinct()

        #인자를 넘겨주기위해 사전형변수? 만들어서 넘겨줌.
        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']

    initial = {'slug': 'do-not-touch'}
    #fields = ['title', 'description', 'content', 'tag']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% block title %}post_all.html{% endblock %}

{% load staticfiles %}
{% block content %}

<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>

<div class="container" id="title">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in posts %}
            <div class="post-preview">
                <a href="{{ post.get_absolute_url }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ post.description }}
                    </h3>
                </a>
                <p class="post-meta">Posted by
                    {{ post.modify_date|date:"N d, Y" }}<br>
                    <a href="{% url 'blog:tagged_object_list' post.tag %}">#{{ post.tag }}</a>
                </p>
            </div>
            <hr>
            {% endfor %}
        <!-- Pager -->
                <div>
                    <span style="float:right;">
        <!-- 현재 페이지를 기준으로 이전 페이지가 있는지 확인 -->
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">PreviousPage / </a>
                    {% endif %}

        <!-- 현재페이지 번호, 총 페이지 개수 -->
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        <!-- 현재 페이지를 기준으로 다음 페이지가 있는지 확인 -->
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number}}"> / NextPage</a>
                    {% endif %}
                    </span>
                </div>

        </div>
    </div>
</div>

<hr>
<script type="text/javascript">window.location.hash = '#title';</script>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends 'base.html' %}

{% block title %}post_archive.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>


<h1 id="content" style="text-align:center;">Post Archives until {% now "N d" %},
    <a class="btn btn-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><h1>{% now 'Y' %}</h1></a>
        <div class="dropdown-menu" >
                {% for date in date_list %}
            <div class="dropdown-item">
                    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}" >{{ date|date:'Y' }}</a>
            </div>
                {% endfor %}
        </div>
</h1>


<br/>
<table class="table table-hover">
    <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Owner</th>
    </tr>
    {% for post in object_list %}
    <tr>
        <td>{{ post.modify_date|date:"Y-m-d" }}</td>
        <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
        <td>{{ post.owner }}</td>
    {% endfor %}
    </tr>
</table>

<script type="text/javascript">window.location.hash='#content'</script>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}

{% block title %}post_archive_day.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>

<center><h1 id="content">Post Archives for {{ day|date:"N d,Y" }}</h1></center>

<br/>

<table class="table table-hover">
    <tr>
        <td>Date</td>
        <td>Title</td>
        <td>Owner</td>
    </tr>
    {% for post in object_list %}
    <tr>
        <td>{{ post.modify_date|date:"Y-m-d" }}</td>
        <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
        <td>{{ post.owner }}</td>
    </tr>
    {% endfor %}
</table>
<script type="text/javascript">window.location.hash="#content"</script>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}

{% block title %}post_archive_month.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>

<h1 id="content" style="text-align:center;">Post Archives for {{ month|date:'N' }}
        <a class="btn btn-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><h1>Day</h1></a>
    , {{ month|date:"Y" }}
        <div class="dropdown-menu" >
                {% for date in date_list %}
            <div class="dropdown-item">
                    <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'b' date|date:'d' %}" >{{ date|date:'d' }}</a>
            </div>
                {% endfor %}
        </div>
</h1>

<br/>

<table class="table table-hover">
    <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Owner</th>
    </tr>
    {% for post in object_list %}
    <tr>
        <td>{{ post.modify_date|date:"Y-m-d"}}</td>
        <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
        <td>{{ post.owner }}</td>
    </tr>
    {% endfor %}
</table>

<script type="text/javascript">window.location.hash='#content'</script>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}

{% block title %}post_archive_year.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>

<h1 id="content" style="text-align:center;">Post Archives for
        <a class="btn btn-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><h1>Month</h1></a>
    , {{ year|date:"Y" }}
        <div class="dropdown-menu" >
                {% for date in date_list %}
            <div class="dropdown-item">
                    <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}" >{{ date|date:'N' }}</a>
            </div>
                {% endfor %}
        </div>
</h1>




<table class="table table-hover">
    <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Owner</th>
    </tr>
    {% for post in object_list %}
    <tr>
        <td>{{ post.modify_date|date:"Y-m-d" }}</td>&nbsp;&nbsp;&nbsp;
        <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
        <td>{{ post.owner }}</td>
    </tr>
    {% endfor %}
</table>
<script type="text/javascript">window.location.hash='#content'</script>
{% endblock %}

blog/templates/blog/post_change_list.html
{% extends 'base.html' %}

{% block title %}post_change_list.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<br/>
<br/>
<div id="content">

    <h1 style="text-align:center;">Post List Change</h1>

    <table class="table table-hover">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'blog:update' item.id%}">Update</a></td>
            <td><a href="{% url 'blog:delete' item.id%}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}post_confirm_delete.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<br/>
<br/>
<div id="content">

    <h1>Post Delete</h1>

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}post_detail.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<br/>
<br/>
<article>
    <div class="container" id="title">
      <div class="row">
        <div class="col-lg-auto col-md-10 mx-auto">


<p class="other_posts">
    {% if object.get_previous_by_modify_date %}
    <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post" style="float:left;">
        &laquo;--{{ object.get_previous_post}}</a>
    {% endif %}

    {% if object.get_next_by_modify_date %}
    <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post" style="float:right;">
        {{ object.get_next_post }}--&raquo;</a>
    {% endif %}
</p>
            <br/>
<div style="text-align:center;"><h1>{{ object.title }}</h1></div>
<p class="date" style="text-align:center;">{{ object.modify_date|date:"j F Y" }}</p>
<br />

<div class="body">
    {{ object.content|linebreaks }}
</div>
        </div>
      </div>
    </div>
</article>
<div>
    <b>TAGS: </b>
    {% load tagging_tags %}
    {% tags_for_object object as tags %}
    {% for tag in tags %}
    <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a>
    {% endfor %}
    <a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>

</div>

<br/>
<div>
    {% load disqus_tags %}
    {% disqus_show_comments %}
</div>

<script type="text/javascript">window.location.hash = '#title';</script>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block title %}post_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<br/>
<br/>
<div id="content">


    <form action="." method="post">
        {% csrf_token %}

        {% if form.errors %}
        <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <h4>This is a creation or update form for your post.</h4>

        <fieldset class="aligned">

            <div class="form-row">
                {{ form.title.label_tag }} {{ form.title }}
            </div>

            <div class="form-row">
                {{ form.slug.label_tag }} {{ form.slug }}
            </div>

            <div class="form-row">
                {{ form.description.label_tag }} {{ form.description }}
            </div>

            <div class="form-row">
                {{ form.content.label_tag }} {{ form.content }}
            </div>

            <div class="form-row">
                {{ form.tag.label_tag }} {{ form.tag }}
            </div>

        </fieldset>

<button type="submit" class="btn btn-primary" style="float: right;">Submit</button>

        <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

blog/templates/blog/post_search.html
{% extends 'base.html' %}
{% block title %}post_search.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/post-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <span class="subheading">Talk about our story ! </span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<br/>
<div id="content">

    <h1 style="text-align:center;">Search</h1><br/>
    <h6 style="text-align:center;">Title / Content / Description</h6>

    <form style="text-align:center;" action="." method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" />
    </form>

    <br/><br/>

    {% if object_list %}
    <div class="container" id="title">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in object_list %}
            <div class="post-preview">
                <a href="{{ post.get_absolute_url }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ post.description }}
                    </h3>
                </a>
                <p class="post-meta">Posted by
                    {{ post.modify_date|date:"N d, Y" }}<br>
                    <a href="{% url 'blog:tagged_object_list' post.tag %}">#{{ post.tag }}</a>
                </p>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>

    {% elif search_term %}
    <div style="text-align:center;"><b><i>Search Word({{ search_term }}) Not Found !</i></b></div>
    {% endif %}
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}