blog/urls.py
from django.conf.urls import url
from .views import *

app_name = 'blog'

urlpatterns = [
    # /blog/
    url(r'^$', PostLV.as_view(), name='index'),
    # /blog/post/ (same as /blog/)
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    # /blog/post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    # /blog/archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    # /blog/2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    # /blog/2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # /blog/2012/nov/18
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # /blog/today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # /blog/tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    # /blog/tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    # /blog/search/
    url(r'^search/$', SearchFormView.as_view(), name='search'),

    # /blog/add/
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    # /blog/change
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    # /blog/pk/update
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name='update'),
    # /blog/pk/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name='delete'),



]

photo/urls.py
from django.conf.urls import url
from .views import *

app_name = 'photo'

urlpatterns = [
    # /photo/
    url(r'^$', AlbumLV.as_view(), name='index'),
    # /photo/album/ same as /photo/
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    # /photo/album/pk/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    # /photo/photo/pk/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # /photo/album/add/
    url(r'^album/add/$', AlbumPhotoCV.as_view(), name='album_add'),
    # /photo/album/change/
    url(r'^album/add/change/$', AlbumChangeLV.as_view(), name='album_change'),
    # /photo/album/pk/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$', AlbumPhotoUV.as_view(), name='album_update'),
    # /photo/album/pk/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),
    # /photo/photo/add/
    url(r'^photo/add/$', PhotoCreateView.as_view(), name='photo_add'),
    # /photo/photo/change/
    url(r'^photo/change/$', PhotoChangeLV.as_view(), name='photo_change'),
    # /photo/photo/pk/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$', PhotoUpdateView.as_view(), name='photo_update'),
    # /photo/photo/pk/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$', PhotoDeleteView.as_view(), name='photo_delete'),

]

photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse


from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/forms.py
from photo.models import *
from django.forms.models import inlineformset_factory

# InlineFormset이란 메인 Form에 딸려있는 하위 Formset.
# 1:N 테이블일 경우 N 테이블의 여러 레코드를 한번에 입력받기 위한 폼.
PhotoInlineFormSet = inlineformset_factory(Album, Photo,
                                           fields=['image', 'title', 'description'],
                                           extra=2
                                           )

photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import *

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from config.views import LoginRequiredMixin

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')

from django.shortcuts import redirect
from .forms import PhotoInlineFormSet

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photo/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        #POST요청일 경우 formset 컨텍스트 변수를 POST, FILES를 이용해 지정. FILES는 파일 업로드가 이뤄지기때문.
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        #GET요청일 경우
        else:
            context['formset'] = PhotoInlineFormSet
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        # formset 객체 구하기
        formset = context['formset']

        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            #form의 데이터를 테이블에 저장. 앨범 레코드 하나 생성
            self.object = form.save()
            #폼셋의 메인 객체를 방금 테이블에 저장한 객체로 지정.
            formset.instance = self.object
            formset.save()
            # get_absolute_url() 호출, 앨범 상세페이지로 이동
            return redirect(self.object.get_absolute_url())
        else:
            #폼셋 데이터가 유효하지 않으면, 메인 폼, 인라인 폼셋 출력, 데이터는 다시보여줌
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photo/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))
# Create your views here.

photo/templates/photo/album_change_list.html
{% extends 'base.html' %}

{% block title %}album_change_list.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    <h1 style="text-align:center;">Album Change</h1>

    <table class="table table-hover">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}

{% block title %}album_confirm_delete.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    <h1>Album Delete</h1>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm"/>
    </form>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends 'base.html' %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">
    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

    <hr/>

    <div class="album-detail">
        {% for photo in object.photo_set.all %}
        <div class="album-detail-photo">
            <a href="{{ photo.get_absolute_url }}">
                <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
            <li>{{ photo.title }}</li>
            <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
        </div>
        {% endfor %}
        <br/>
        <br/>
        <br/>
        <br/>
    </div>

</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}

{% block title %}album_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">


    <!-- form 이나 formset이 multipart 인코딩이 필요한지 여부 확인 -->
    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the FORM error(s) below.</p>
    {% endif %}
    {% if formset.errors %}
    <p class="errornote">Wrong! Please correct the FORMSET error(s) below.</p>
    {% endif %}


    <h4>Create or Update Album contents.</h4>

    <fieldset class="aligned">
        <div class="form-row">
            {{ form.name.label_tag }} {{ form.name }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>

    <h4>Create or Update Photo contents.</h4>

    <!-- 폼셋에 들어 있는 각 폼을 다루는 경우, {{ formset.management_form }} 변수 반드시 추가.
        django의 템플릿 엔진이 폼셋에 들어있는 폼의 개수를 알아야 하기 때문-->
    {{ formset.management_form }}
    {% for form in formset %}
        {{ form.id }}
    <fieldset class="aligned">
        <div class="form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>
        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
    </fieldset>
    {% endfor %}

     <button type="submit" class="btn btn-primary" style="float: right;">Submit</button>
    <script type="text/javascript">window.location.hash = '#content';</script>

    </form>

</div>
{% endblock %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    {% for item in object_list %}

    <div class="clear_float">
        <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
        &emsp;<b><i>{{ item.description }}</i></b>
    </div>

    <hr/>

    <div class="album-list">
        {% for photo in item.photo_set.all|slice:":5" %}
        <div class="album-list-photo">
            <a href="{{ photo.get_absolute_url }}">
                <img class="img-thumbnail" src="{{ photo.image.url }}" />
            </a>
        </div>
        {% endfor %}
        <br/>
        <br/>
        <br/>
    </div>
    {% endfor %}
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}photo_change_list.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    <h1 style="text-align:center;">Photo Change</h1>
    
    <table class="table table-hover">
        <tr>
            <th>Album</th>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    
        {% for item in object_list %}
        <tr>
            <td><a href="{{ item.album.get_absolute_url }}">{{ item.album }}</a></td>
            <td><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    <h1>Photo Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">

    <h2>{{ object.title }}</h2>

    <table class="photo-detail">
        <tr>
            <td>
                <a href="{{ object.image.url }}">
                    <img style="max-width:100%" src="{{ object.image.url }}"/>
                </a>
            </td>

            <td>
                <ul>
                    <li>Photo Description</li>
                    {% if object.description %}
                        <p>{{ object.description|linebreaks }}</p>
                    {% else %}
                        <p>(blank)</p>
                    {% endif %}
                    <li>Date Uploaded</li>
                    <p>{{ object.upload_date }}</p>
                    <li>Album Name</li>
                    <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
                </ul>
            </td>
        </tr>
    </table>
</div>
<script type="text/javascript">window.location.hash = '#content';</script>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends "base.html" %}

{% block title %}photo_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/Nature.jpeg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Photo</h1>
                        <span class="subheading">Share your Photo !</span>
                    </div>
                </div>
            </div>
        </div>
  </header>
<div id="content">


    {% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" action="">
    {% else %}
    <form method="post" action="">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <h4>This is a creation or update form for your photo.</h4>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>

        <div class="form-row">
            {{ form.album.label_tag }} {{ form.album }}
            <button type="button"><a href="{% url 'photo:album_add' %}">Add Album</a></button>
        </div>
    
        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>

        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

    </fieldset>

    <button type="submit" class="btn btn-primary" style="float: right;">Submit</button>

    <script type="text/javascript">document.getElementById('id_album').focus();</script>

    </form>

</div>
{% endblock %}