blog/urls.py
from django.conf.urls import url
from .views import *

app_name = 'blog'

urlpatterns = [
    # /blog/
    url(r'^$', PostLV.as_view(), name='index'),
    # /blog/post/ (same as /blog/)
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    # /blog/post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    # /blog/archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    # /blog/2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    # /blog/2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # /blog/2012/nov/18
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # /blog/today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # /blog/tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    # /blog/tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    # /blog/search/
    url(r'^search/$', SearchFormView.as_view(), name='search'),

    # /blog/add/
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    # /blog/change
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    # /blog/pk/update
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name='update'),
    # /blog/pk/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name='delete'),



]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from config.views import HomeView
from config.views import UserCreateView, UserCreateDoneTV


urlpatterns = [
    path('admin/', admin.site.urls),
    #Django의 URLconf를 갖와 사용.
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

]

photo/urls.py
from django.conf.urls import url
from .views import *

app_name = 'photo'

urlpatterns = [
    # /photo/
    url(r'^$', AlbumLV.as_view(), name='index'),
    # /photo/album/ same as /photo/
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    # /photo/album/pk/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    # /photo/photo/pk/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # /photo/album/add/
    url(r'^album/add/$', AlbumPhotoCV.as_view(), name='album_add'),
    # /photo/album/change/
    url(r'^album/add/change/$', AlbumChangeLV.as_view(), name='album_change'),
    # /photo/album/pk/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$', AlbumPhotoUV.as_view(), name='album_update'),
    # /photo/album/pk/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),
    # /photo/photo/add/
    url(r'^photo/add/$', PhotoCreateView.as_view(), name='photo_add'),
    # /photo/photo/change/
    url(r'^photo/change/$', PhotoChangeLV.as_view(), name='photo_change'),
    # /photo/photo/pk/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$', PhotoUpdateView.as_view(), name='photo_update'),
    # /photo/photo/pk/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$', PhotoDeleteView.as_view(), name='photo_delete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>{% block title %}Django Web Programming{% endblock %}</title>

    {% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/css/clean-blog.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">yeknoDjango</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Bookmark</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'bookmark:index' %}">List</a>
                            <a class="dropdown-item" href="{% url 'bookmark:add' %}">Add</a>
                            <a class="dropdown-item" href="{% url 'bookmark:change' %}">Edit</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'blog:index' %}">List</a>
                            <a class="dropdown-item" href="{% url 'blog:add' %}">Add</a>
                            <a class="dropdown-item" href="{% url 'blog:change' %}">Edit</a>
                            <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                            <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Photo</a>
                        <div class="dropdown-menu">
                            <div class="dropdown-header">Photo</div>
                            <a class="dropdown-item" href="{% url 'photo:index' %}">List</a>
                            <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Add</a>
                            <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo Change</a>
                            <div class="dropdown-divider"></div>
                            <div class="dropdown-header">Album</div>
                            <a class="dropdown-item" href="{% url 'photo:album_add' %}">Add</a>
                            <a class="dropdown-item" href="{% url 'photo:album_change' %}">Edit</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div>
      <!-- 로그인 되어 있으면 is_active는 True 반환-->
        {% if user.is_active %}
        <div class="welcome">Welcome,
            <!-- firstof 는 False가 아닌 첫 인자를 선택.-->
            <strong>{% firstof user.get_short_name user.get_username %}</strong><br/>
            <a href="{% url 'password_change' %}">Change Password</a> /
            <a href="{% url 'logout' %}">Logout</a>
        </div>
        {% else %}
        <h6 class="welcome">Welcome, Anonymous <br/>
            <a href="{% url 'login' %}">Login</a> /
            <a href="{% url 'register' %}">Register</a>
        </h6>
        {% endif %}
        </div>
    </nav>


{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

  <!-- Footer -->
  <footer>
    <div class="container">

        <div style="text-align:center;">
          <p class="copyright text-muted">Copyright &copy; Donkey 2019</p>
            <p class="text-muted">Email : anbo1028@naver.com / anbo10283182@gmail.com</p>
        </div>

    </div>
  </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'bootstrap/js/clean-blog.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}


{% block content %}

<!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static "img/home-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Donkey Blog</h1>
                        <span class="subheading">Fill in my blog's contents. please</span>
                    </div>
                </div>
            </div>
        </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <a href="{% url 'bookmark:index' %}">
            <h2 class="post-title">
              Bookmark
            </h2>
              <br/>
            <h3 class="post-subtitle">
              Show my bookmark !<br/>
                <br/>
                And if you want to recommend a new bookmark for me,
                Register here.
            </h3>
          </a>
        </div>
        <hr>
        <div class="post-preview">
          <a href="{% url 'blog:index' %}">
            <h2 class="post-title">
              Blog
            </h2>
              <br/>
              <h3 class="post-subtitle">This is not only mine.<br/><br/>
              Fill in Together !</h3>

          </a>
        </div>
        <hr>
        <div class="post-preview">
          <a href="{% url 'photo:index' %}">
            <h2 class="post-title">
              Photo
            </h2>
              <br/>
            <h3 class="post-subtitle">
              You can upload photos here.<br/><br/>
                If you want to add a albums ? You can also do it !
            </h3>
          </a>

  <hr>
{% endblock content %}

{% block footer %}

{% endblock footer %}

templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'bootstrap/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Man must explore, and this is exploration at its greatest
            </h2>
            <h3 class="post-subtitle">
              Problems look mighty small from 150 miles up
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on September 24, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
            </h2>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on September 18, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Science has not yet mastered prophecy
            </h2>
            <h3 class="post-subtitle">
              We predict too much for the next year and yet far too little for the next ten.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on August 24, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Failure is not an option
            </h2>
            <h3 class="post-subtitle">
              Many say exploration is part of our destiny, but it’s actually our duty to future generations.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on July 8, 2019</p>
        </div>
        <hr>
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'bootstrap/js/clean-blog.min.js' %}"></script>

</body>

</html>